# Generated by Django 3.0.3 on 2020-04-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200409_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
