# Generated by Django 3.0.3 on 2020-04-06 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('pdffile', models.FileField(upload_to='pdf')),
                ('written_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_date', models.DateTimeField()),
                ('category', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='slides')),
                ('sequence', models.IntegerField()),
                ('text', models.TextField()),
                ('time_min', models.IntegerField(default=0)),
                ('time_sec', models.IntegerField(default=0)),
                ('pdffile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.PDF')),
            ],
        ),
    ]
